# Generated by Django 3.2 on 2022-03-25 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField(max_length=120)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('filed_cat', models.CharField(choices=[('FASHION', 'fashion'), ('BEAUTY', 'beauty'), ('TRAVEL', 'travel'), ('FOOD + DRINK', 'food + drink'), ('SCHOOL LIFE', 'school life'), ('COLLAGE LIFE', 'collage life'), ('FAMILY', 'family'), ('FITNES', 'fitnes'), ('MUSIC', 'music'), ('REEL', 'reel'), ('MOVIES', 'movies'), ('TECHNOLOGY', 'technology'), ('FINANCE', 'finance'), ('SCIENCE', 'science'), ('NEWS', 'news'), ('PETS', 'pets'), ('OTHER', 'other'), ('NONE', 'none')], default='none', max_length=50)),
                ('image_blog', models.ImageField(default=None, max_length=300, null=True, upload_to='blog_img/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(related_name='posts', to='blog.Tag')),
            ],
            options={
                'ordering': ['-modified_at'],
            },
        ),
    ]
